jobs:
  include:
    - stage: "Test"
      name: "Lint"
      language: node_js
      node_js: 8
      script:
        - npm run jsonlint
        - npm run svglint
    - name: "Test package"
      language: node_js
      node_js: 8
      script:
        - npm run test

notifications:
  email:
    on_success: never
    on_failure: change
